### ISSUE TITLE
qvality qvalues: calculated with PEPs or decoys? 

### ISSUE THREAD

**Issue by adder** [percolator/percolator#122]
Good morning,
It's not clear to me from the qvality help if the qvalues that are returned in the output are calculated by looking at the decoy counts above a certain treshold or if they are calculated using the PEPs calculated by qvality. Both methods are outlined in the qvality paper.

Thanks

**Comment by percolator** [comment]
Hi, yes, we might want to change the help so that it reflect how we
calculate the q-values. I added the following text:

intro << "The method reports score, PEP, and q-value calculated
directly from scores" << endl;
intro << "Convergence of the method can be checked by comparing the
average PEP of identifications" << endl;
intro << "above threshold with the q-value" << endl;

commit: 4bdbb69076bd344f584ebe4271bea8182eeb1433

On Tue, Mar 17, 2015 at 6:46 AM, adder <notifications@github.com> wrote:
> Good morning,
> It's not clear to me from the qvality help if the qvalues that are returned
> in the output are calculated by looking at the decoy counts above a certain
> treshold or if they are calculated using the PEPs calculated by qvality.
> Both methods are outlined in the qvality paper.
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub.



-- 
========================
Lukas Käll
http://kaell.org
Royal Institute of Technology - KTH
Science for Life Laboratory
School of Biotechnology
Box 1031, 171 65 Solna, Sweden
+46 8 52481196 or
+46 76 9425179

**Comment by adder** [comment]
Thanks for the clarification!

Just to be clear. With q-values calculated directly from scores, you mean taking the average PEP of targets above a certain treshold as described in the paper? With the second sentence, you can maybe give the impression that it's calculated otherwise and you can verify this first method by comparing it with the average PEP of indentifications.

Thanks

**Comment by percolator** [comment]
No, we calculate the q-value from the scores, i.e. the target and decoy
scores or the p-values if such are provided. That is different from
calculating the q-value from PEPs. One can check the convergence of
qvality's logistic regression by comparing the average PEP to the q-value.

On Tue, Mar 17, 2015 at 12:35 PM, adder <notifications@github.com> wrote:

> Thanks for the clarification!
>
> Just to be clear. With q-values calculated directly from scores, you mean
> taking the average PEP of targets above a certain treshold as described in
> the paper? With the second sentence, you can maybe give the impression that
> it's calculated otherwise and you can verify this first method by comparing
> it with the average PEP of indentifications.
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/percolator/percolator/issues/122#issuecomment-82295126>
> .
>



-- 
========================
Lukas Käll
http://kaell.org

**Comment by adder** [comment]
Ah okey,
I think I got it.
Sorry for the confusion. I also sometimes use the PEP as a score. 
So based on the ranking of the scores and the fraction of decoys above some score
 treshold with monotonicity constraints. Or the 'FDR-derived q-values' from your 2008 qvality paper. 

Thanks and have a nice day,
