### ISSUE TITLE
tandem2pin assigns the "decoy" label incorrectly for shared peptides

### ISSUE THREAD

**Issue by markmipt** [percolator/percolator#143]
tandem2pin sets the label to "-1" (decoy) for peptides shared between target and decoy proteins in some cases. I noticed that it happens when a decoy protein has more identified spectra than alternative target protein. For example, if X!Tandem identifies peptides shared between a target protein and a decoy, but the decoy has more unique identified peptides, then the shared peptides will be marked as decoy. The correct behavior seems to be to mark the shared peptides as target (which sometimes happens, e.g. when no unique peptides are found for the two proteins).

**Comment by MatthewThe** [comment]
Thank you for reporting this issue. 

It's been a while since I've looked at the X!Tandem output, but it could be that we derive the label from the best scoring protein, which - as you pointed out - could lead to a decoy label for shared peptides if the decoy protein has many identified spectra. The fix would be to assign the label only after all proteins have been seen, which should be quite straightforward. I will keep you updated here.

**Comment by markmipt** [comment]
Thank you very much! I've tested a new version and it works now just as expected.
