### ISSUE TITLE
why q-value is greater than FDR in final results?

### ISSUE THREAD

**Issue by 01joy** [percolator/percolator#155]
I run Percolator3.0 with the following command:
```
percolator.exe -F 0.01 -t 0.05 file.perc.txt > file.perc.validated.txt
```
But in file.perc.validated.txt, there are many PSMs whose q-values are greater than 0.05. Why?

-F 0.01: select training data in 1% fdr
-t 0.05: filter final result in 5% fdr
Am I right?

**Comment by MatthewThe** [comment]
Not quite, the `-t`/`--testFdr` option is only used to **count** the number of significant PSMs. This threshold is used to select the best hyperparameters during cross validation and also to report the final number of significant PSMs/peptides.

If you only want PSMs/peptides below a certain q-value threshold, you will have to filter the output file yourself in a postprocessing step. 

Also, note that if you want to have q-values on PSM-level, rather than the default peptide-level, you will have to use the `-U` option.

**Comment by 01joy** [comment]
I still don't understand the option `-F` and `-t`, could you please explain it. 

What's more, if I just want the results in 5% FDR, what do I have to do?

Thanks.

**Comment by MatthewThe** [comment]
If you just want results at 5% FDR, these options will not be of any help. To create such a list, you can just keep all PSMs/peptides in the output for which the q-value (the third column in the output) is below 0.05 and throw out the rest. The PSMs are sorted by this column, so it will be easy to find the first PSM with a q-value above 0.05 and delete all rows below.

I'm not sure what your use case is, but I have the feeling you might not need the `-F` and `-t` flag, as they pertain more to the inner workings of the Percolator algorithm, rather than the output file. Anyway, a short explanation of the two flags in case you are still interested in them.

The `-F` option sets the FDR threshold for selecting positive training examples from the target PSMs. 

The `-t` option sets the FDR threshold to evaluate the performance of different combinations of hyperparameters in the cross validation process. Furthermore, it is also the threshold used for reporting the number of PSMs/peptides that are printed to the terminal.

**Comment by 01joy** [comment]
Hi, thank you MatthewThe for your detailed replay.

I thought the same way like you, but I doubted myself as only ~200 PSMs are below 5% FDR out of ~700 PSMs.  Now you clear up my confusion.

Thanks.
