### ISSUE TITLE
understanding concatenated searches and TDC

### ISSUE THREAD

**Issue by jvolkening** [percolator/percolator#181]
I'm evaluating percolator 3.01 to perform FDR calculation as part of a pipeline. It's unclear to me how it handles evaluation of concatenated target/decoy search results. The help text for the `-Y` flag says:

> "If the input PSMs are detected to be coming from a concatenated search, this option will be turned on automatically"

However, the STDERR output run on such a search says this (even if I explicitly give the `-Y` flag):

> Concatenated search input detected, skipping both target-decoy competition and mix-max.

which seems to contradicate the help text. Can you provide any clarity on how this is handled?

Also, there is quite a bit of difference in the number of PSMs at a given FDR for the different methods. Using the same input data, I got the following PSM counts at 2% FDR:

concat_search(with or without `-Y`): 7221
separate_search/tdc: 6791
separate_search/mix-max: 6383

My interpretation of other comments in the percolator papers and in other issue threads was that applying TDC to separate-search results should have the same effect as using a concatenated search, but clearly I'm not understanding this properly. Any help would be greatly appreciated.

**Comment by MatthewThe** [comment]
We have revised the logic and error messages in a commit (40f6798) after the 3.01 release, after earlier complaints from other users regarding this issue:

The new help message regarding the -Y flag:

> Replace the mix-max method by target-decoy competition for assigning q-values and PEPs. If the input PSMs are from separate target and decoy searches, Percolator's SVM scores will be used to eliminate the lower scoring target or decoy PSM(s) of each scan+expMass combination. If the input PSMs are detected to be coming from a concatenated search, this option will be turned on automatically, as this is incompatible with the mix-max method. In case this detection fails, turn this option on explicitly.

So to summarize: -Y enforces that the mix-max procedure is skipped, but since it detected a concatenated input, this was done anyway. If it had detected separate searches it would - in addition - have run Percolator's TDC procedure.

Regarding your performance figures:
- it is indeed surprising that Percolator's TDC procedure performs so much worse than a concatenated search. Does this behavior persist on peptide level? One reason could be that Percolator's TDC procedure only allows one PSM for each scan+expMass combination, which could decrease the number of PSMs compared to a concatenated search if you allow multiple hits per spectrum.
- we have also observed that mix-max is performing worse than tdc on separate searches and are currently looking into this

Hope that answers (some of) your questions.

**Comment by jvolkening** [comment]
Thanks for the quick reply.

> it is indeed surprising that Percolator's TDC procedure performs so much worse than a concatenated search. Does this behavior persist on peptide level?

concat_search: 5017 target peptides
sep_search/tdc: 4614 target peptides

I am using Comet for searching and using Comet's facilities for automated concatenated or separate decoy searching (however, I have tested by manually building the databases with similar results). The **only** difference between the two results above is switching the Comet `decoy_search` parameter from 1 to 2. Percolator seems to be properly detecting the difference. My percolator calls for concatenated search and separate search, respectively, are:

`percolator -t 0.02 -m test.concat.psm.tsv -r test.concat.pep.tsv test.concat.pin`
`percolator -Y -t 0.02 -m test.sep.psm.tsv -r test.sep.pep.tsv test.sep.pin`

I have put the stdout for the calls here:

[concatenated search](https://gist.github.com/jvolkening/9d09edfedb997dc8be3d1dc87fb0d709)
[separate search](https://gist.github.com/jvolkening/94d2bad18b906ed09c6dc8859ca88b27)

I guess I'm wondering if the percolator devs have any recommendations regarding best practice for their software. The numbers for separate_search/tdc are similar to what I see with e.g. PeptideProphet at the same FDR. I was initially excited to see the numbers from the concatenated search analysis but am a bit worried that the higher number of passing PSMs are due to my misuse of the software somehow.

**Comment by MatthewThe** [comment]
I can indeed reproduce your results on some data of my own. We are investigating this further, I'll try to get back to you next week.

**Comment by dub2s** [comment]
I performed a separate target decoy search in crux and then processed the file in percolator. If I use the -Y flag ( for tdc ), then I am not getting any positive hit while if I just remove it then I am getting 25 positive peptides. Also, in tdc mode, whatever testfdr I set, decoy list is empty.
Somehow, on crux website -Y flag is used in the example even though the search was done separately. 

[tdc stderr, target psms, decoy psms](https://gist.github.com/dub2s/5d3ad244cadaf84c4645780dca23ceeb)

[mixmax stderr, target psms, decoy psms](https://gist.github.com/dub2s/f8501ddaf2c0671f80af8c9ce81c9ee5)

**Comment by trishorts** [comment]
I am not sure if this is a separate issue question or not. I'll let you decide.

I am doing a concatenated search and supplying PSM search results to percolator, which uses a fixed score cut-off on the bottom end. It is my understanding that in any concatentated search, the number of targets will exceed the number of decoys by the number of true positives. 

I always get a message of the following sort. Which seems wrong because I am not doing separate searches....

![image](https://user-images.githubusercontent.com/16841846/81002345-af4d8180-8e0e-11ea-9c61-94ebc006e12d.png)

**Comment by MatthewThe** [comment]
You can override this automatic detection by using the `--search-input` argument. We try to detect the type of input (concatenated or separate) based on the scan numbers provided. If we see duplicate scan numbers, we assume it's a separate search. This may fail in case you combine multiple runs, which may cause duplicate scan numbers even if you do a concatenated search.

**Comment by trishorts** [comment]
Thanks.
i couldn't find that on this page https://github.com/percolator/percolator/wiki/Command-line-options
is it listed somewhere else?

**Comment by MatthewThe** [comment]
You can find all the current command line parameters by executing `percolator -h`. 

The page you refer to needs to be updated, thanks for raising that issue!

**Comment by trishorts** [comment]
I appreciate your prompt help. Really makes a difference. Have a good day.

**Comment by jmueller95** [comment]
Hey all,
I have another question that I think is related to this topic. 
I'm using Percolator subsequently to Comet. Right now, my pipeline looks as follows: 
I have a database that already includes decoy sequences, so I'm setting Comet's `decoy_search` parameter to `0`. I keep the top 10 PSMs per Spectrum (which doesn't necessarily mean 5 target & 5 decoy, since Comet doesn't care that the databases are mixed).
Before running Percolator, I'm adding some custom scores as additional features to my PSMs. I then want to rerank them using Target Decoy Competition on PSM level, so I'm using both the `-Y` and `-U` flag. My question is: Am I allowed to give Percolator all 10 PSMs of each Spectrum when using TDC (i.e. will my q values be valid), or should I apply a filter beforehand and only input the Top Target and Top Decoy PSM? Or would you advise to use separate target/decoy databases overall?

**Comment by MatthewThe** [comment]
The q-values should be valid, as they are calculated on the PSM list after applying TDC.

**Comment by jmueller95** [comment]
That's great to know, thanks for the quick reply!
