### ISSUE TITLE
tandem2pin labels all peptides as decoy

### ISSUE THREAD

**Issue by tivdnbos** [percolator/percolator#210]
Dear all, 

First I have searched with X!Tandem against a target and decoy database separately, after which I use tandem2pin to create a .tsv file. I use the following command:

``tandem2pin -P REVERSED -o my_output_file.tsv ./tandem-fwd.t.xml ./tandem-rev.t.xml``

All fasta headers in the reversed database (and reversed search results in ./tandem-rev.t.xml) are labeled with REVERSED. But, when looking to my_output_file.tsv, tandem2pin has labeled everything as decoy.
Any idea of what could be the problem?

Best regards, 
Tim

**Comment by MatthewThe** [comment]
If you used separate searches, you don't have to specify the `-P` flag, `tandem2pin` will simply assume the first file specified is the target search and the second the decoy search. 

Having said that, it probably still does not work if you remove the flag. Would it be possible to share the files or otherwise a minimum example that shows the same behavior?

**Comment by MatthewThe** [comment]
Please send it to matthew [dot] the [at] scilifelab [dot] se

**Comment by tivdnbos** [comment]
Thanks, the files have been sent.

**Comment by tivdnbos** [comment]
I am using Ubuntu 16.10 and percolator version v.3.01.0. I'll try with an update of Percolator.

**Comment by tivdnbos** [comment]
With the latest percolator version, v.3.02, the problem is solved!

**Comment by MatthewThe** [comment]
Great!
