### ISSUE TITLE
Why after protein grouping, there are same proteins in multiple groups?

### ISSUE THREAD

**Issue by fcyu** [percolator/percolator#211]
Hi,

I tried to do the protein grouping using the option 
`--protein-decoy-pattern DECOY_ --picked-protein swissprot.TD.fasta --results-proteins out,protein.tsv`

It looks like there was no error and warning. But I found that there were some proteins exist in different groups. My question is that is protein grouping supposed to assign a protein to only one protein group?

Thanks,

Fengchao

**Comment by MatthewThe** [comment]
Protein grouping should only assign a protein to a single protein group, so something is going wrong. Could you share input and output files of a case where this happens?

**Comment by fcyu** [comment]
Thanks for your prompt reply. Attached please find all files.

[test.zip](https://github.com/percolator/percolator/files/1796116/test.zip)

**Comment by MatthewThe** [comment]
The problem is that the proteins in the percolator input files are separated by semicolons, whereas they should be separated by tabs. How did you generate these input files, did you use any of our converters?

As a side note, also the peptide sequences are not formatted as expected with extra indicators for the peptide terminals `R.nGGGGGGGGGGGFPSRc.G` should be `R.GGGGGGGGGGGFPSR.G`.

**Comment by fcyu** [comment]
Thanks for your explanation. I write the converters by myself since there are upstream analysis. I will change the format.

By the way, does the additional "n" and "c" effect the results? If not, I prefer to keep it,

Thanks

**Comment by MatthewThe** [comment]
Alright, the "n" and "c" could affect the protein level results, because percolator detects `R.nGGGGGGGGGGGFPSRc.G` as a semi-tryptic peptide, even though it is tryptic. We group proteins based on an in-silico digest of the fasta file depending on the type of digestion we detect. The protein grouping might therefore be slightly different, though in practice the effect is probably limited.

**Comment by fcyu** [comment]
Thanks for your reply. Since the effect is limited, I decided not to change it because the changing will affect my whole analysis pipeline. 

By the way, Comet's pin output may also have "n" or "c" if there is a modification one the terminus,

Thanks

**Comment by MatthewThe** [comment]
Okay, thanks for the warning! I will check if we need to accomodate this.
