### ISSUE TITLE
Percolator 3 new protein inference issue

### ISSUE THREAD

**Issue by sdgroeve** [percolator/percolator#213]
Hi

I'm evaluating the new protein inference in Percolator 3 (which I think is great).
I'm running into a 
Exception caught: basic_string::substr
stop of the program.
It only does this in some cases, most cases work.

This is a .pin file for which Percolator stops:
[result.zip](https://github.com/percolator/percolator/files/1958942/result.zip)

I ran it as 
percolator -i 5 -f auto -l result.omega_percolator3_proteins.tsv result.pin
I use 3.02 on Ubuntu 16.

I tried to figure out what could be wrong for a few days now...please help...

**Comment by MatthewThe** [comment]
The problem is the decoy PSM 5001 with the peptide X.EIKNAIKEVK.X and protein P17697. Each decoy peptide should have at least one protein prefixed with the decoy pattern specified by the -P/--protein-decoy-pattern flag (which by default is set to "random_").

Nonetheless, we should exit more gracefully than this, I will add an extra check for the decoy pattern.

Some other points of caution: 
* if you don't care about the flanks, set them to `-` instead of `X`, e.g. `-.EIKNAIKEVK.-`
* the picked protein method only works well if you use a reversed protein database, where the reversed protein is named `<decoy_pattern><original_protein>`, e.g. `random_sp|P35232|PHB_HUMAN`

**Comment by sdgroeve** [comment]
Thank you! 
A bug in my code caused a decoy peptide to be assigned to a target protein.
That solved the problem.
