### ISSUE TITLE
Error during mac os build

### ISSUE THREAD

**Issue by mtstahl** [percolator/percolator#233]
I get the following error when running `./osx_build.sh` on MacOS Mojave:
`/opt/local/bin/ranlib: object: libeludelibrary.a(RetentionFeatures.cpp.o) malformed object (unknown load command 1)`

Is there a known solution?

**Comment by MatthewThe** [comment]
A quick google search of this error suggests that this problem might occur after upgrading to Mojave due to outdated `ranlib` and `ar` binaries, which were likely installed using macports as part of the `cctools` package. Did you do a macports migration (https://trac.macports.org/wiki/Migration)?

Otherwise, the most common solution (though perhaps a bit drastic..) seems to be to backup/delete these binaries installed by macports:
```
$ sudo mv /opt/local/bin/ranlib /opt/local/bin/ranlib-backup
$ sudo mv /opt/local/bin/ar     /opt/local/bin/ar-backup
```
This should force the use of the system `ranlib` and `ar` binaries instead.

**Comment by mtstahl** [comment]
Thanks Matthew,

I did the migration, now it's working.
