### ISSUE TITLE
The theory of the p-value calculation?

### ISSUE THREAD

**Issue by lhuangjs** [percolator/percolator#237]
I am attempting to figure out the workflow of `Fido`. However, I cannot find the description of `grid search` in the paper(*Efficient Marginalization to Compute Protein Posterior Probabilities from Shotgun Mass Spectrometry Data*). So I start to view the source code. But I cannot understand the `p-value calculation`. Why do you make this judgment `myPair->first != (myPair+1)->first`? And can you give me some help about `p-value calculation`? Thanks!
https://github.com/percolator/percolator/blob/aaab4d0bf9f98377cc64567ac45bea5eea1a8102/src/PosteriorEstimator.cpp#L488

In addition, the source code suggests a protein group is `decoy protein` when all proteins in an identical group are `decoy proteins` otherwise it is `target protein`. But the paper suggested a protein group containing both targets and decoys are not counted in evaluation.
https://github.com/percolator/percolator/blob/aaab4d0bf9f98377cc64567ac45bea5eea1a8102/src/FidoInterface.cpp#L559

**Comment by MatthewThe** [comment]
If I'm not mistaken, the percolator implementation is indeed a little bit different from the original paper.

The grid search is mentioned in the paper, see the paragraph starting with "Our probability model requires the estimation of three free parameters...". However, the range over which these parameters are searched is chosen differently, I think, based on empirical tests.

The `myPair->first != (myPair+1)->first` evaluation is to make sure that we put proteins with the same score receive the same p-value. I'm not sure where the p-value calculation procedure is described, but perhaps it's in the original percolator paper. The idea is, however, that the decoys form a uniform distribution between 0 and 1 of the p-values. Therefore, for the targets, we can use the (number of decoys with lower score + 1)/(number of total decoys + 1) as the p-value estimate.

In the percolator code base a group with both targets and decoys is indeed counted as a target, contrary to the Dido paper. However, as the Fido paper also mentions this does not result in significant differences in practice.

**Comment by wsnoble** [comment]
Here is a response from Oliver, who originally wrote Fido:

I believe this is going through and computing the percentage of decoys
found at every protein score threshold (where proteins are sorted with
highest posterior first).

posSame and negSame are the targets and decoys at an exact score threshold
(respectively). So if the ranking has
0.9 target_A
0.9 target_B
0.9 decoy_X,
eventually, we will get posSame=2 and negSame=1 for the score threshold 0.9.

The code is doing something tricky to avoid a quadratic algorithm: it is
going through all protein scores (in descending order), and only making an
"update" to the vector p when we come to the end of the ranking or when the
score threshold changes.

That is what the linked line does:
myPair+1 == combined.end() checks if we're on the last entry (myPair is an
iterator, and so +1 gives the next iterator) and
myPair->first != (myPair+1)->first) checks if the score threshold has
changed at all.

The reason for needing the score threshold to change is that in the ranking
above, target_A and target_B are listed before decoy_X, but since they are
all tied at posteriors of 0.9, the ordering is arbitrary. Because of this,
it is unfair to count any of them first (often this will defer to a
lexicographic ordering on the labels themselves, subtly preferring either
target or decoy accessions in the sort). So they must all either be
included or excluded from the computation.

When that if statement does execute, then it appends the predicted number
of decoys at the score threshold. In the ranking above, each protein would
give a 1/3 decoy rate, so we would interpolate
1/3 decoys if only one protein at 0.9 were included
2/3 decoys if only two proteins at 0.9 were included
3/3 decoys if all three proteins at 0.9 were included.
This is added to nDecoys, the cumulative decoy count thus far. So if we had
10 decoys appear with posteriors >0.9, then the number of decoys near the
0.9 threshold would have
..., 10, 10.3333, 10.66666, 11, ...

The final transform line is dividing these decoy counts by the final decoy
count, thereby turning them into a false positive rate. Ultimately, it
appears that's what this function does.
