### ISSUE TITLE
what is the function of the app percolator-noxml and elude?

### ISSUE THREAD

**Issue by lhuangjs** [percolator/percolator#240]
I install percolator with `deb`. I download the installation package from [Releases](https://github.com/percolator/percolator/releases/download/rel-3-02-01/ubuntu64.tar.gz). I got 4 `deb` file after decompression. I used `dpkg` to install apps in the following order.
```
elude-v3-02-linux-amd64.deb
percolator-converters-v3-02-linux-amd64.deb
percolator-v3-02-linux-amd64.deb
percolator-noxml-v3-02-linux-amd64.deb
```
However, I cast a problem when I install `percolator-noxml-v3-02-linux-amd64.deb`. what is the function of the app `percolator-noxml` and `elude`?

**Comment by MatthewThe** [comment]
* `elude` is a package for retention time prediction, it's not needed for percolator.
* `percolator-noxml` is the same as the `percolator` package (which is why you probably get problems installing both) but does not support the xml input format. It has the advantage of not having to rely on the XML parsing libraries, but if the regular `percolator` package works fine for you, there's no need to install this.
* `percolator-converters` contains converters to turn search engine output into the percolator input format.
