### ISSUE TITLE
building percolator 

### ISSUE THREAD

**Issue by bernt-matthias** [percolator/percolator#250]
I'm currently trying to build percolator for bioconda (https://github.com/bioconda/bioconda-recipes/pull/16532). 

During building converters the following error occurs

```
-- Checking for module 'tokyocabinet'
--   Found tokyocabinet, version 1.4.48
CMake Error at CMakeLists.txt:133 (message):
   The package Tokyo Cabinet has not been found
```

Building is done like this: 
https://github.com/bioconda/bioconda-recipes/blob/e9ed6500c0d75c139a24ae1607fbed0406fb40d4/recipes/percolator/build.sh#L10

Is there a special variable that I need to set?

Note that if I set -DSERIALIZE="Boost" building works. So I was wondering if I can use just this. 

You also document boost as default here:

https://github.com/percolator/percolator/blob/48b5424766078cd1e6eba805ee584c2a5064a9db/src/converters/CMakeLists.txt#L33

But use tokyocabinet for building packages

https://github.com/percolator/percolator/blob/48b5424766078cd1e6eba805ee584c2a5064a9db/admin/builders/centos64_build.sh#L72

**Comment by MatthewThe** [comment]
That's a bit strange, perhaps the directory structure of tokyocabinet has been changed at some point such that the cmake script can't find some specific files.

Nevertheless, it should be fine to use boost instead of tokyocabinet. There might be some benefits in terms of memory usage with tokyocabinet, but for most use cases there won't be a noticeable difference.

**Comment by bernt-matthias** [comment]
OK Thanks. Then we will go with boost I guess.
