### ISSUE TITLE
An exception occurred: Error in the input data: cannot find an initial direction with positive training examples. Consider setting/raising the initial training FDR threshold (--train-initial-fdr). Terminating.

### ISSUE THREAD

**Issue by javanOkendo** [percolator/percolator#253]
I am wondering how to solve this problem. Anyone with a suggestion on how to solve this?
An exception occurred: Error in the input data: cannot find an initial direction with positive training examples. Consider setting/raising the initial training FDR threshold (--train-initial-fdr).
Terminating.

**Comment by MatthewThe** [comment]
Have you tried setting the `--train-initial-fdr` flag? You could for example add `--train-initial-fdr 0.1`, or even `--train-initial-fdr 0.2` if the problem persists. Do you expect relatively few (<100) correct PSMs?

**Comment by MartinChiaHsinLiu** [comment]
Hi Matthew,
I also use percolator v3 and meet a similiar problem as JavanOkendo. 
I have a question about how many correct PSMs should be the minimal requirement for Percolator?

**Comment by MatthewThe** [comment]
Unfortunately, I can't give you an exact minimum number. The check that is made here is that after sorting by one of your input features, for the top X PSMs (`X = 1, ..., total num PSMs`) the ratio between decoy and target features is below `--train-initial-fdr` (or `--train-fdr` if `--train-initial-fdr` is not specified).

For example, if you sort by the search engine score and the top 20 PSMs consist of 1 decoy and 19 targets, the error would occur if `--train-initial-fdr` is 0.05 (since `FDR = 1/19 = 0.053`), but not for 0.1. This calculation is repeated for each top X PSMs and for each input feature sorted both in ascending and descending order.

Hope that helps!

**Comment by jcharkow** [comment]
Hi, I'm not sure if this has previously been addressed but I noticed that the error message says `--train-initial-fdr` while I believe the actual parameter that should be changed is called `--train-fdr-initial` (words, "fdr" and "initial" are swapped)

**Comment by percolator** [comment]
Thanks for reporting this! I fixed the error message. --Lukas
