### ISSUE TITLE
compatibility issue with v3.6

### ISSUE THREAD

**Issue by micgrab** [percolator/percolator#329]
Hello.

I have a problem running percolator v3.6 on a file that worked with v3.5.

## Part 1
To reproduce the issue here is a toy data set:
```
SpecId	Label	ScanNr	ExpMass	Mass	feature_1	Peptide	Protein1
34292	-1	88	1103.59885	1103.59885	0.2029	KGPYLHPHR	_placeholder_
97071	-1	89	1103.59885	1103.59885	0.3172	KGPYLHPHR	_placeholder_
127175	1	110	1485.78140	1485.78140	0.1040	RAHERPPPHPHR	_placeholder_
181611	1	112	2469.91930	2469.91930	0.0123	STGHGGHCTNCQDNTDGAHCER	_placeholder_
113801	1	239	1646.73185	1646.73185	0.0065	EHTGKPTTSSSEACR	_placeholder_
237191	1	245	2041.96648	2041.96648	0.2799	KTEEERPQETTNQHSTK	_placeholder_
105065	-1	249	919.46241	919.46241	0.1106	RNPASYGR	_placeholder_
96772	1	256	1088.50982	1088.50982	0.0867	ESESTAAAPAR	_placeholder_
96773	-1	256	1444.78989	1444.78989	0.0169	GRPPKQEPAAAAPR	_placeholder_
127254	1	258	1488.77972	1488.77972	0.0047	SVQPQSHKPQPTR	_placeholder_
127255	1	258	1490.72260	1490.72260	0.0685	GTHDRDPSEKPPR	_placeholder_
141975	1	262	1488.77972	1488.77972	0.0040	SVQPQSHKPQPTR	_placeholder_
74393	1	263	1386.68516	1386.68516	0.4173	SPEQSRSSPEKR	_placeholder_
127960	1	264	1122.61456	1122.61456	0.4747	LSHPTTSRPK	_placeholder_
74104	1	266	1386.68516	1386.68516	0.0389	SPEQSRSSPEKR	_placeholder_
74105	-1	266	1844.87520	1844.87520	0.0768	KLKDSEETHETGAASDK	_placeholder_
87069	1	267	1764.80270	1764.80270	0.0012	NRPEPHSDENGSTTPK	_placeholder_
175837	1	268	2173.87443	2173.87443	0.0025	NHSGNDERDEEDEERESK	_placeholder_
49377	1	269	1498.70120	1498.70120	0.0016	ESRPENEEERPK	_placeholder_
```
The prcolator versions are [percolator-v3-06-linux-amd64.deb](https://github.com/percolator/percolator/releases/download/rel-3-06/percolator-v3-06-linux-amd64.deb) and [percolator-v3-05-linux-amd64.deb](https://github.com/percolator/percolator/releases/download/rel-3-05/ubuntu.tar.gz)

The command I used was `percolator -Y toy_data.tsv` and it shows this error:  
`Couldn't find Protein header in tab-file`

But there is a Protein header and the changelog does not mention that anything about the input format has changed. The Wiki also shows an [example](https://github.com/percolator/percolator/wiki/Interface#pintsv-tab-delimited-file-format) with "proteinId1". This header does also work with v3.5 but not with v3.6.

I looked into the [code](https://github.com/percolator/percolator/blob/master/src/DataSet.cpp#L314) and it seems like that now the header name needs to be `Proteins`. I also noticed that even when you use `Proteins` as header but you misspelled `Label` as e.g. `label`, then you will also get the same error: `Couldn't find Protein header in tab-file`.

## Part 2
So I changed the header and percolator works again, but now I get a lot of warnings:  
```
...
Features:
Mass feature_1 
Warning: Set decoy prefix don't match
Warning: Set decoy prefix don't match
Warning: Set decoy prefix don't match
Warning: Set decoy prefix don't match
Warning: Set decoy prefix don't match
Found 19 PSMs
...
```
What does this error mean? What do I need to do to get rid of it?

Also, the result changed.
with v3.5 I get:
```
PSMId	score	q-value	posterior_error_prob	peptide	proteinIds
175837	0	0.125	0.205014	NHSGNDERDEEDEERESK	_placeholder_
...
```

with v3.6 I get:
```
PSMId	score	q-value	posterior_error_prob	peptide	proteinIds
175837	0	0.125	0.205014	NHSGNDERDEEDEERESK	
...
```
The entries of the proteins are missing here.

-----
I hope you can help me.

**Comment by percolator** [comment]
Thank you for reporting the error. Would you be able to share the dataset
you used when the problem occurred?

--Lukas

**Comment by MatthewThe** [comment]
Seems like the problem was with the proteinIds not being printed out correctly (#242). 
For me, it works as expected now.

**Comment by picciama** [comment]
For other people who just want to get a solution / reason without debugging for 2 hours:

This is an unfortunate combination of a breaking change and a misleading error message. You simply need to name your column "Proteins" and it works. 

This line in release 3.06:
https://github.com/percolator/percolator/blob/4f8f6f6f3bc20a0239a1dc054337b4a5980922d1/src/DataSet.cpp#L414
has been forgotten to be updated in order to reflect the change from "Protein" to "Proteins".

However, this is fixed already on the master branch:
https://github.com/percolator/percolator/blob/c34cafbb2f0a96b921ab86b4626980cbf25719da/src/DataSet.cpp#L426

Also, the check is now case insensitive:
https://github.com/percolator/percolator/blob/c34cafbb2f0a96b921ab86b4626980cbf25719da/src/DataSet.cpp#L318
which solves capitalization issues but if you happen to have no "label" column the above error message will be printed despite a "Proteins" column present.
 
@MatthewThe this is sth. you should definitely change, i.e. check which of "proteins" and "labels" is missing and print the correct message accordingly as such:

```C
int return_error = 0
if (proteinIndex==-1) {
    if (VERB > 0) {
        std::cerr << "Couldn't find 'Proteins' column in tab-file" << std::endl;
    }
    return_error = 1
if (labelIndex==-1){
    if (VERB > 0) {
        std::cerr << "Couldn't find 'Label' column in tab-file" << std::endl;
    }
    return_error = 1
if (return_error==1) {
    return "error";
}
```

The question remains, why this breaking change was necessary, which now requires checking the version in our package for backward compatibility. I propose to you that you also allow protein as a valid column name and do so also for label(s) should you consider to change that too :)
