### ISSUE TITLE
Protein Ids missing for some identifications

### ISSUE THREAD

**Issue by kfattila** [percolator/percolator#342]
Hi, 

I have just updated and compiled the percolator, but it looks like the protein IDs are missing for some identifications. I am using a make-pin.pin file as an input and it contains the Protein ID correctly, but it isn't available in the output. For instance, this is a line in the input:
`target_0_7648_2_1	1	7648	1965.0727	1965.0654	0.69314718	0.82280302	0.80805397	4.94423580	2899.40405273	0.78125000	17	0	1	0	1	1	0	7.21081829	0.00363823	0.00363823	R.VQHEVIELTATIDQLQK.D	F07A5.7a`
The last field is the protein ID, but it is missing from the output:
`target_0_7648_2_1	1.95614	0.000699343	6.45072e-06	R.VQHEVIELTATIDQLQK.D	`

I note that the protein ID is present for most identifications. I also observe the same in the PSMs output and in the peptide output files.
Am I doing something wrong or is this a bug in percolator?

I am attaching the input and the output files. 
[percolator.target.peptides.txt](https://github.com/percolator/percolator/files/9607442/percolator.target.peptides.txt)
[make-pin.pin.txt](https://github.com/percolator/percolator/files/9607449/make-pin.pin.txt)

The command line I used:
 ~/percolator --results-peptides tide-xcorr/percolator.target.peptides.txt --decoy-results-peptides tide-xcorr/percolator.decoy.peptides.txt --results-psms tide-xcorr/percolator.target.psms.txt --decoy-results-psms tide-xcorr/percolator.decoy.psms.txt  make-pin.pin

Thanks a lot!

**Comment by sdgroeve** [comment]
Hello,

I have the same problem. I'm using 3.6 as:
`percolator --subset-max-train 5000000 --maxiter 5 --verbose 2 --results-psms  result.out --decoy-results-psms result.decoy --trainFDR 0.01 --protein-decoy-pattern decoy_ --picked-protein concat.fasta --results-proteins result.proteins.tsv --weights result.weights --protein-enzyme trypsin --spectral-counting-fdr 0.01 --unitnorm --only-psms --post-processing-tdc --protein-report-duplicates --protein-report-fragments  --decoy-results-proteins proteins_decoy.tsv --protein-report-duplicates --protein-report-fragments input.pin`

There is also an issue with the protein result file. In the pin I have proteins matched with many peptides that are not in the protein result file. E.g. UBE2C. This protein is present twice (with one of them a subset of the other), so I can see this is a special case, but at least one of them should be reported no?

The pin file and result files are attached.
[files.zip](https://github.com/percolator/percolator/files/10090337/files.zip)

Thank you for your reply!

**Comment by bmx8177** [comment]
I have also come across this issue on the most recent version of Percolator. To me it appears that the column does not have a value when the peptide is only found in a single protein.

**Comment by wsnoble** [comment]
@bmx8177 can you see if the problem is still there when you get rid of all the extraneous command line options?  Can you check to see if it's still there if you remove the "filename" column from the input file?

**Comment by bmx8177** [comment]
@wsnoble Yes, the problem is there under both conditions you asked for.

/home/lina627/bin/percolator/Release/src/percolator --results-psms percolator.target.psms.txt ../make-pin/make-pin.pin

/home/lina627/bin/percolator/Release/src/percolator --results-psms percolator.target.psms.remove-filename.txt make-pin-remove-filename.pin

[percolator.target.psms.remove-filename.txt](https://github.com/percolator/percolator/files/11161776/percolator.target.psms.remove-filename.txt)
[percolator.target.psms.txt](https://github.com/percolator/percolator/files/11161777/percolator.target.psms.txt)
[make-pin-remove-filename.pin.txt](https://github.com/percolator/percolator/files/11161781/make-pin-remove-filename.pin.txt)
[make-pin.pin.txt](https://github.com/percolator/percolator/files/11161784/make-pin.pin.txt)
