### ISSUE TITLE
Strange behaviour of --subset-max-train

### ISSUE THREAD

**Issue by sdgroeve** [percolator/percolator#373]
Hi,

I believe I found a bug. 
When I run (.pin included):
$ percolator --maxiter 5 --verbose 2 --trainFDR 0.01 --unitnorm --post-processing-tdc result.pin
all is fine

When I add --subset-max-train:
percolator --subset-max-train 500000 --maxiter 5 --verbose 2 --unitnorm --post-processing-tdc result.pin
The score and PEP columns have value -nan. 

Percolator version 3.06.4

[result.zip](https://github.com/percolator/percolator/files/14238357/result.zip)

**Comment by MatthewThe** [comment]
I can indeed reproduce the error, will try to find out what's going wrong.

**Comment by sdgroeve** [comment]
Thnx!

**Comment by MatthewThe** [comment]
The problem was actually not (directly) related to the `--subset-max-train` flag. It also happened without this flag, depending on the random seed.

It was the result of two very specific problems: 
1. the decoys mainly had high scan numbers. As PSMs are distributed over the cross validation bins in ascending scan number order, this resulted in several cross validation bins already being "full" when the last decoys were distributed over the cross validation bins.
2. the rescaling of SVM scores before merging the results from the 3 cross validation bins aims to set the median decoy score to -1.0 and the score of the PSM at the FDR cutoff (e.g. 1%) to 0.0. In your case, there were so few decoys that the median decoy score was higher than the PSM at the FDR cutoff. This is what in the end resulted in the nan scores.

I now implemented two fixes:
1. shuffle the PSMs prior to assigning them to cross validation bins.
2. added a check that throws an error if it sees this case and advises to lower `--trainFDR`. In case the `--no-terminate` flag is set, it applies an offset such that median decoy has score -1.0, but skips rescaling.
