### ISSUE TITLE
Coredump on osx - potentially boost related

### ISSUE THREAD

**Issue by percolator** [percolator/percolator#76]
I'm to use sqt2pin on my mac.  I downloaded the dmg files for 2.05 and installed percolator then the converters.  When I try to do a sqt2pin call though i get the following:

Seans-MacBook-Pro:2014_01_28 smcilwain$ sqt2pin ./v07539_UofF_malaria_TMT_1.mzXML.gz/comet.target.sqt
Pin-converter version 2.05, Build Date Nov 12 2013 14:02:19
Copyright (c) 2013 Lukas Käll. All rights reserved.
Written by Lukas Käll (lukas.kall@scilifelab.se) in the
School of Biotechnology at KTH - Royal Institute of Technology, Stockholm.
Issued command:
sqt2pin ./v07539_UofF_malaria_TMT_1.mzXML.gz/comet.target.sqt

boost::filesystem::path codecvt to wstring: error

Any idea what is going on?

Thanks,
Sean

**Comment by MatthewThe** [comment]
Since the 3.0 release we have included a temporary fix using [std::tmpnam](http://en.cppreference.com/w/cpp/io/c/tmpnam). However, there is a [theoretical chance this fails, as well as a security issue](http://stackoverflow.com/questions/21295974/are-there-any-reasons-to-avoid-using-tmpnam-to-get-a-name-for-a-temporary-file). Somehow changing to [std::tmpfile](http://www.cplusplus.com/reference/cstdio/tmpfile/) would be better, but it does not seem possible to directly pass file handles to TokyoCabinet and LevelDB.
